== pytest-pexpect

Pytest pexpect plugin.

=== Installation

You can install `pytest-pexpect` via `pip`

.From local sources (specify directory)
----
pip3 install pytest-pexpect/
----

.To remove
----
pip3 uninstall pytest-pexpect
----

Add into `conftest.py` line  `pytest_plugins: str = ("pytest_pexpect")` or
add into `pytest.ini` lines

----
[pytest]
addopts = -p pytest_pexpect
----

Find if plugin is active: `pytest --trace-config`

=== Parameters

`--pexpect-dry-run` - if added to command line, `pexpect` commands (`sendline`, `expect` ) are not performed

=== Quick start

.Use `pexpect_shell` fixture
[source,python]
----
def test_pexpect_object(pexpect_shell):
    pexpect_shell.sendline('echo "Hello pexpect"')
    pexpect_shell.expect('Hello pexpect', timeout=2)
----

The `log` directory is created with output.

== Tests

Run full `tox` tests

[source,bash]
----
tox
----

Run full `tox`  `flake8`  tests
[source,bash]
----
tox -e flake8
----

Run  `pytest` tests

[source,bash]
----
pytest -o log_cli=true -o log_cli_level=WARNING  tests/
----


=== PLAN

* code documentation
* examples
* `pip` package
* support for test documentation (record `sendline` and `expect` commands)


=== Links


pytest     https://pytest.org
pexpect    https://github.com/pexpect/pexpect

=== License

Distributed under the terms of the `MIT`_ license, "pytest-pexpect" is free and open source software
